[package]
name = "wisp-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "nyx-server"
path = "src/main.rs"

[dependencies]
wisp-tokio = { path = "../wisp-tokio" }
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "macros", "sync", "time"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring", "tls12", "logging"] }
rustls-pki-types = { version = "1", features = ["std"] }
clap = { version = "4", features = ["derive"] }
ed25519-dalek = "2"
hex = "0.4"

[dev-dependencies]
wisp-core = { path = "../wisp-core" }
tokio-tungstenite = { version = "0.24", features = ["rustls-tls-webpki-roots"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring", "tls12", "logging"] }
futures-util = "0.3"
sha2 = "0.10"
rcgen = "0.13"
